site_name: Culvert Analysis Toolkit
nav: 
  - Install: install.md
  - Data Prep Guides:
    - data-overview.md
    - data-naacc-table.md
    - data-noaa-rainfall.md
    - data-curve-number-raster.md
    - data-dem.md
  - Analysis Guides:
    - analysis-overview.md
    - capacitycalc-run-one.md
    - capacitycalc-results.md
  - Calculators:
    - calcs-peak-flow.md
    - calcs-culvert-capacity.md
  - Develop: dev.md

theme:
  name: mkdocs
  navigation_depth: 3
