site_name: Culvert Analysis Toolkit
nav: 
  # - index.md
  - Install: install.md
  - Data Prep Guide:
    - data-overview.md
    - naacc-table.md
    - noaa-rainfall.md
    - curve-number-raster.md
    - dem-rasters.md
  - Analysis Guide:
    - analysis-overview.md
    - run-one.md
    - run-batch.md
  - Calculators:
    - peak-flow.md
    - culvert-capacity.md
  - Develop: dev.md

theme:
  name: mkdocs
  navigation_depth: 3
