site_name: Culvert Analysis Toolkit
nav: 
  - index.md
  - installation.md
  - toolbox.md
  - Data Guide:
    - data-overview.md
    - naacc-table.md
    - noaa-rainfall.md
    - curve-number-raster.md
    - dem-rasters.md
  - Analysis Guide:
    - analysis-overview.md
    - run-one.md
    - run-batch.md
  - Development:
    - dev-setup.md
    - dev-project-structure.md
    - peak-flow.md
    - culvert-capacity.md
theme:
  name: mkdocs
  navigation_depth: 3
